### ISSUE TITLE
1.20.4 fabric crash on startup

### ISSUE THREAD

**Issue by EfficientStinkbug** [NecroCrab/dinos-1.20.1#2]
[crash-2024-05-09_11.05.20-client.txt](https://github.com/NecroCrab/dinos-1.20.1/files/15260243/crash-2024-05-09_11.05.20-client.txt)

**Comment by NecroCrab** [comment]
Looks like an issue with the fishes, very strange.
Have you tried running it standalone?

**Comment by EfficientStinkbug** [comment]
Thanks for the reply!  Actually I haven't, but so far my 150+ mods work without issue by themselves.

**Comment by EfficientStinkbug** [comment]
[crash-2024-05-31_21.41.07-client.txt](https://github.com/user-attachments/files/15520756/crash-2024-05-31_21.41.07-client.txt)
Sorry to not be of much help, but the newest version also crashes on startup, but for a different reason. (So far I haven't seen anyone with a similar problem, but maybe it'll be helpful for you)
